# Generated by Django 5.2.2 on 2025-06-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PpName', models.CharField(max_length=20)),
                ('Pprice', models.IntegerField()),
                ('Pcolor', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
