# Generated by Django 4.2.2 on 2023-08-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(choices=[('HW', 'height/Weight'), ('BP', 'Blood Pressure'), ('HR', 'Heart Rate')], max_length=30)),
                ('componentValue', models.CharField(max_length=30)),
                ('measureDateTime', models.DateTimeField(auto_now_add=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.patient')),
            ],
        ),
    ]
