# Generated by Django 5.2.2 on 2025-06-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Color', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Launch', models.DateField()),
            ],
        ),
    ]
